name: Selenium tests
run-name: Run ${{github.event.inputs.test_category}} test 

on:
  schedule:
  - cron: '45 17 * * *'
  #push:
    #branches: [ "CiCd" ]
  workflow_dispatch:
   inputs:
     test_category: 
      description: 'Select test category' 
      type: choice
      options:
      - All
      - Common
      - Project
      - RandomError
      required: true 
    


jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: ubuntu-latest  
                            

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://dl.google.com/linux/direct/google-chrome-beta_current_amd64.deb
        sudo apt-get install -y ./google-chrome-beta_current_amd64.deb
        sudo apt-get -y --no-install-recommends install -f  # Установить зависимости, если необходимо
      


    - name: Execute All tests 
      if: github.event.inputs.test_category == 'All'
      run: |
        dotnet restore
        dotnet test 

    - name: Execute Common tests 
      if: github.event.inputs.test_category == 'Common'
      run: |
        dotnet restore
        dotnet test --filter Category=Common

    - name: Execute Project tests 
      if: github.event.inputs.test_category == 'Project'
      run: |
        dotnet restore
        dotnet test --filter Category=Project

    - name: Execute RandomError tests 
      if: github.event.inputs.test_category == 'RandomError'
      run: |
        dotnet restore
        dotnet test --filter Category=RandomError


    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: HomeworkTMS/bin/Debug/net8.0/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history

    - name: List files
      run: ls -R

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with: 
          name: project
          path: HomeworkTMS/bin/Debug

  